In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('datasets/pokemon_alopez247.csv')
df

,Number,Name,Type_1,Type_2,Total,HP,Attack,Defense,Sp_Atk,Sp_Def,...,Color,hasGender,Pr_Male,Egg_Group_1,Egg_Group_2,hasMegaEvolution,Height_m,Weight_kg,Catch_Rate,Body_Style
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,...,Green,True,0.875,Monster,Grass,False,0.71,6.9,45,quadruped
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,...,Green,True,0.875,Monster,Grass,False,0.99,13.0,45,quadruped
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,...,Green,True,0.875,Monster,Grass,True,2.01,100.0,45,quadruped
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,...,Red,True,0.875,Monster,Dragon,False,0.61,8.5,45,bipedal_tailed
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,...,Red,True,0.875,Monster,Dragon,False,1.09,19.0,45,bipedal_tailed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,717,Yveltal,Dark,Flying,680,126,131,95,131,98,...,Red,False,NaN,Undiscovered,NaN,False,5.79,203.0,45,two_wings
717,718,Zygarde,Dragon,Ground,600,108,100,121,81,95,...,Green,False,NaN,Undiscovered,NaN,False,5.00,305.0,3,serpentine_body
718,719,Diancie,Rock,Fairy,600,50,100,150,100,150,...,Pink,False,NaN,Undiscovered,NaN,True,0.71,8.8,3,head_arms
719,720,Hoopa,Psychic,Ghost,600,80,110,60,150,130,...,Purple,False,NaN,Undiscovered,NaN,False,0.51,9.0,3,head_only
720,721,Volcanion,Fire,Water,600,80,110,120,130,90,...,Brown,False,NaN,Undiscovered,NaN,False,1.70,195.0,3,quadruped

In [14]:
list = []

for column in df.columns:
    list.append((len(df[column].unique()), column, df[column].dtype))

print(list)

[(721, 'Number', dtype('int64')), (721, 'Name', dtype('O')), (18, 'Type_1', dtype('O')), (19, 'Type_2', dtype('O')), (183, 'Total', dtype('int64')), (94, 'HP', dtype('int64')), (100, 'Attack', dtype('int64')), (97, 'Defense', dtype('int64')), (94, 'Sp_Atk', dtype('int64')), (90, 'Sp_Def', dtype('int64')), (101, 'Speed', dtype('int64')), (6, 'Generation', dtype('int64')), (2, 'isLegendary', dtype('bool')), (10, 'Color', dtype('O')), (2, 'hasGender', dtype('bool')), (8, 'Pr_Male', dtype('float64')), (15, 'Egg_Group_1', dtype('O')), (14, 'Egg_Group_2', dtype('O')), (2, 'hasMegaEvolution', dtype('bool')), (50, 'Height_m', dtype('float64')), (398, 'Weight_kg', dtype('float64')), (33, 'Catch_Rate', dtype('int64')), (14, 'Body_Style', dtype('O'))]

In [16]:
df2 = df

lbl_encod = LabelEncoder()

for column in df2.columns:
    if column == 'Number' or column == 'Name':
        continue
    df2[column] = lbl_encod.fit_transform(df[column])

def scale_using_rule_of_three(column):
    max_val = column.max()
    conversion_factor = 10 / max_val
    scaled_values = column * conversion_factor
    return scaled_values

# Apply rule of three scaling to each column from the third column to the last one
scaled_data = df2.iloc[:, 2:].apply(scale_using_rule_of_three, axis=0)

scaled_data.columns

<bound method NDFrame.describe of        Type_1     Type_2     Total        HP    Attack   Defense    Sp_Atk  \
0    5.294118   7.222222  3.131868  1.827957  2.424242  2.395833  4.408602
1    5.294118   7.222222  5.164835  3.333333  3.737374  3.854167  5.913978
2    5.294118   7.222222  9.065934  5.483871  5.656566  5.729167  7.526882
3    3.529412  10.000000  2.802198  1.182796  2.727273  1.875000  3.870968
4    3.529412  10.000000  5.164835  3.118280  3.939394  3.333333  5.913978
..        ...        ...       ...       ...       ...       ...       ...
716  0.588235   3.888889  9.945055  8.817204  9.292929  6.666667  9.569892
717  1.176471   5.555556  9.780220  7.741935  7.272727  8.333333  6.021505
718  8.823529   2.222222  9.780220  2.258065  7.272727  9.375000  7.526882
719  8.235294   4.444444  9.780220  5.483871  8.181818  3.541667  9.892473
720  3.529412   9.444444  9.780220  5.483871  8.181818  8.229167  9.462366

       Sp_Def  Speed  Generation  ...     Color  hasGender    Pr_Male  \
0    4.157303    2.4         0.0  ...  3.333333       10.0   7.142857
1    5.617978    3.7         0.0  ...  3.333333       10.0   7.142857
2    7.415730    5.7         0.0  ...  3.333333       10.0   7.142857
3    2.471910    4.2         0.0  ...  7.777778       10.0   7.142857
4    4.157303    5.7         0.0  ...  7.777778       10.0   7.142857
..        ...    ...         ...  ...       ...        ...        ...
716  7.191011    7.3        10.0  ...  7.777778        0.0  10.000000
717  6.966292    7.0        10.0  ...  3.333333        0.0  10.000000
718  9.662921    2.9        10.0  ...  5.555556        0.0  10.000000
719  9.213483    4.7        10.0  ...  6.666667        0.0  10.000000
720  6.629213    4.7        10.0  ...  2.222222        0.0  10.000000

     Egg_Group_1  Egg_Group_2  hasMegaEvolution  Height_m  Weight_kg  \
0       7.142857     4.615385               0.0  1.224490   1.234257
1       7.142857     4.615385               0.0  2.040816   2.216625
2       7.142857     4.615385              10.0  4.081633   7.833753
3       7.142857     1.538462               0.0  1.020408   1.586902
4       7.142857     1.538462               0.0  2.244898   2.846348
..           ...          ...               ...       ...        ...
716     7.857143    10.000000               0.0  8.571429   9.068010
717     7.857143    10.000000               0.0  7.959184   9.521411
718     7.857143    10.000000              10.0  1.224490   1.662469
719     7.857143    10.000000               0.0  0.816327   1.687657
720     7.857143    10.000000               0.0  3.469388   8.891688

     Catch_Rate  Body_Style
0        1.5625    6.923077
1        1.5625    6.923077
2        1.5625    6.923077
3        1.5625    0.000000
4        1.5625    0.000000
..          ...         ...
716      1.5625    9.230769
717      0.0000    7.692308
718      0.0000    2.307692
719      0.0000    4.615385
720      0.0000    6.923077

[721 rows x 21 columns]>

<bound method NDFrame.describe of 0       9
1       9
2       9
3       6
4       6
       ..
716     1
717     2
718    15
719    14
720     6
Name: Type_1, Length: 721, dtype: int64>